### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Barathwaja**

### CODE REVIEW

**Review by sandeshghanta — CHANGES_REQUESTED** [review]
Can you please give more examples for the /statistics method.

**Comment by Barathwaja** [comment]
Can you please explain clearly what that is? what is the need clearly then i can add more examples

**Comment by Barathwaja** [comment]
Check now .

**Comment by sandeshghanta** [comment]
Thanks for working on this issue

**Comment by Barathwaja** [comment]
No problem.

**Pull request merged**
